### ISSUE TITLE
Implement card displayer

### ISSUE THREAD

**Issue by Jammyjamjamman** [TelluricDeckay/telluricdeckay#3]
Implement method for displaying the card to show.
Similar to: 
https://github.com/TelluricDeckay/telluric-handeval/blob/a6bf123903802908ebae470c286f2ae3d20587c0/src/lib.rs#L20-L36 , but should return an `Iced` Image-like struct.

**Comment by andy5995** [comment]
Except for the card backs, this was committed to #2 

https://github.com/TelluricDeckay/telluricdeckay/pull/2/commits/d5d4292d9a21d205f2e8c6a858ddbdcc9f1ec1e3

https://github.com/TelluricDeckay/telluricdeckay/pull/2/commits/423ba7bf7571648a3bbf3859824397a3d3cd76d9

**Comment by Jammyjamjamman** [comment]
Was implemented here: https://github.com/TelluricDeckay/telluricdeckay/pull/16
Some improvements can be made, but it's implemented. So I consider this ticket "done".
